name: Greeting

on:
  issues:
    types: ["opened"]

jobs:
  greeting:
    name: Send Greeting
    runs-on: ubuntu-latest
    # only send message to users not (yet) associated with repo
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    if: github.event.issue.author_association == 'NONE'

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 1

      - name: Render template
        id: template
        uses: chuhlomin/render-template@204ce622bc2fd5c787ff5ca885ff19fb577e7a41
        with:
          template: .github/comment-template.md
          vars: |
            author: ${{ github.actor }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.template.outputs.result }}
