name: Verify GCR Login

on:
  schedule:
    - cron: "5 1 * * *" # daily

  workflow_dispatch:

jobs:
  login:
    name: Verify GCR Login
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - id: login_to_gcp
        uses: google-github-actions/auth@e8df18b60c5dd38ba618c121b779307266153fbf
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
